server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    user: sa
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      encoding: utf-8